import type { Metadata } from 'next';
import { Playfair_Display, Capriola } from 'next/font/google';
import './globals.css';
import Nav from './components/Nav';

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
});

const capriola = Capriola({
  subsets: ['latin'],
  variable: '--font-capriola',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${capriola.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
